version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web-servers

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      - PORT=3001
      - DaTABASE_URL=postgresql://postgres:admin@db:5432/postgres
    ports:
      - "3001:3001"
    networks:
      - web-servers

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
  
volumes:
  pgdata:

