services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders
      - wordpress
      - app

  orders:
    image: nginxdemos/hello

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysqlWordpress:3306
      WORDPRESS_DB_USER: wordpressUser
      WORDPRESS_DB_PASSWORD: wordpressPass
      WORDPRESS_DB_NAME: wordpressDB
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://localhost/wordpress');
        define('WP_SITEURL','http://localhost/wordpress');
        define('WP_ALLOW_REPAIR', true); 
    depends_on:
      - mysqlWordpress
    volumes:
      - wordpress_data:/var/www/html

  mysqlWordpress:
    image: mysql:8.4.8 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: wordpressUser
      MYSQL_PASSWORD: wordpressPass
      MYSQL_DATABASE: wordpressDB
    volumes:
      - mysql_data_wordpress:/var/lib/mysql

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - DBVolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: NextCloudPassword
      MYSQL_DATABASE: NextCloudDB
      MYSQL_USER: NextCloudUser

  app:
    image: nextcloud:latest
    restart: always
    depends_on:
      - db
    volumes:
      - NextCloudVolume:/var/www/html
    environment:
      MYSQL_PASSWORD: NextCloudPassword
      MYSQL_DATABASE: NextCloudDB
      MYSQL_USER: NextCloudUser
      MYSQL_HOST: db
      OVERWRITEWEBROOT: /app
      OVERWRITECLIURL: http://localhost/app

volumes:
  mysql_data_wordpress:
  wordpress_data:
  NextCloudVolume:
  DBVolume: