services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Proxy/index.html:/usr/share/nginx/html/index.html:ro

  auth-service:
    image: auth-service:latest
    build:
      context: ./Auth
  
  order-service:
    image: order-service:latest
    build:
      context: ./Order