# frontend/nginx.conf
# لا نستخدم directive "user" لأننا نشغل كـ non-root
# user nginx;  # علق على هذا السطر أو احذفه

worker_processes auto;

# غير مسار pid إلى مجلد يملكه user nginx
pid /tmp/nginx.pid;

error_log /var/log/nginx/error.log notice;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    # upstreams
    upstream backend_upstream {
        server backend:3001;
    }

    include /etc/nginx/conf.d/*.conf;
}